apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rolling
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: module10
  template:
    metadata:
      labels:
        app: module10
    spec:
      containers:
      - name: module10.1
        image: aumit373/module10:ostad-test
        ports:
        - containerPort: 3000
