apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: module10-app-bg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Aumit373/module10.git
    targetRevision: main
    path: all_deploy/blue_green
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true