apiVersion: apps/v1
kind: Deployment
metadata:
  name: module10-app-stable
spec:
  replicas: 4   # majority of traffic goes here
  selector:
    matchLabels:
      app: module10
      version: stable
  template:
    metadata:
      labels:
        app: module10
        version: stable
    spec:
      containers:
      - name: module10
        image: aumit373/module10:ostad-test   # stable image
        ports:
        - containerPort: 3000