apiVersion: apps/v1
kind: Deployment
metadata:
  name: module10-app-blue
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: module10
      color: blue
  template:
    metadata:
      labels:
        app: module10
        color: blue
    spec:
      containers:
        - name: module10-bg
          image: aumit373/module10:v1.0
          ports:
            - containerPort: 5000
