apiVersion: apps/v1
kind: Deployment
metadata:
  name: module10-app-bg
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: module10-app-bg
      color: green
  template:
    metadata:
      labels:
        app: module10-app-bg
        color: green
    spec:
      containers:
        - name: module10-bg
          image: aumit373/module10:v2.0
          ports:
            - containerPort: 5000
