apiVersion: v1
kind: Service
metadata:
  name: module3-service
spec:
  type: NodePort
  selector:
    app: module3
    version: blue   # Change this to "green" when switching
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080