apiVersion: v1
kind: Service
metadata:
  name: module10-service
  namespace: apps
spec:
  type: NodePort
  selector:
    app: module10-app-bg
    version: blue   # Change this to "green" when switching
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080